const fakeHotels = [
  {
    id: 1,
    hotelName: "Light bright airy stylish apt & safe peaceful stay",
    guests: 4,
    bedrooms: 2,
    bed: 2,
    bath:2,
    cancellation: "Cancellation fexibility availiable",
    facilities: "Wif Air conditioning Kitchen",
    ratting: 4.9,
    photo:'https://iili.io/2oywTx.png',
    price: 34,
  },
  {
    id: 2,
    hotelName: "Apartment in Lost Panorama",
    guests: 3,
    bedrooms: 1,
    bed: 1,
    bath:3,
    cancellation: "Cancellation fexibility availiable",
    facilities: "Wif Air conditioning Kitchen",
    ratting: 4.8,
    photo:'https://iili.io/2oyOQV.png',
    price:38,
  },
  {
    id: 3,
    hotelName: "AR Lounge & Pool (r&r + b&b)",
    guests: 4,
    bedrooms: 2,
    bed: 2,
    bath:3,
    cancellation: "Cancellation fexibility availiable",
    facilities: "Wif Air conditioning Kitchen",
    ratting: 4.5,
    photo:'https://iili.io/2oyNhQ.png',
    price: 45,
  },
];

export default fakeHotels;